/**
 * RtlPreview: spec §3.2 step 3-4.
 *
 * Drafted RTL is SHOWN before synthesis, never auto-submitted. Two actions:
 * "Looks good, synthesize" or "Edit" (turns the block into an editable
 * textarea, at which point the beginner is effectively on the expert path
 * for this file, feeding the same endpoint).
 */
import { useState } from "react";
import { CodeBlock } from "../../common/CodeBlock";
import { Icon } from "../../common/Icon";

interface RtlPreviewProps {
  rtlCode: string;
  onChange(code: string): void;
  onConfirm(): void;
  onDiscard(): void;
  busy: boolean;
}

export function RtlPreview({ rtlCode, onChange, onConfirm, onDiscard, busy }: RtlPreviewProps) {
  const [editable, setEditable] = useState(false);
  return (
    <div className="rtl-preview">
      <div className="rtl-disclaimer" role="note">
        <Icon name="sparkles" size={16} />
        <p>
          <strong>This code was generated by an AI model from your description.</strong> Review it, or ask an expert
          on your team to, before continuing.
        </p>
      </div>

      {editable ? (
        <div className="field">
          <label className="label" htmlFor="rtl-edit">
            Edit RTL
          </label>
          <textarea
            id="rtl-edit"
            className="textarea input-mono rtl-editor"
            value={rtlCode}
            onChange={(e) => onChange(e.target.value)}
            spellCheck={false}
            rows={18}
          />
        </div>
      ) : (
        <CodeBlock code={rtlCode} language="verilog" label="drafted.v · read-only" />
      )}

      <div className="row">
        <button type="button" className="btn btn-primary" onClick={onConfirm} disabled={busy || !rtlCode.trim()}>
          <Icon name="check" size={14} /> Looks good, synthesize
        </button>
        <button type="button" className="btn btn-secondary" onClick={() => setEditable((e) => !e)} disabled={busy}>
          <Icon name="code" size={14} /> {editable ? "Done editing" : "Edit"}
        </button>
        <span className="spacer" />
        <button type="button" className="btn btn-ghost" onClick={onDiscard} disabled={busy}>
          Discard draft
        </button>
      </div>
    </div>
  );
}
